### ISSUE TITLE
Add make mappings

### ISSUE THREAD

**Issue by AsafFisher** [doronz88/fa#46]
Some embedded device has memory mappings... would be cool to have a signature for that so that the offset and section name will be disconnected automatically

This can be done using `add_segm`

**Comment by doronz88** [comment]
I failed to understand what the intention is. If you need to modify the regions, sounds like it should be done while creating the idb in the first place. Probably by creating a proper elf to represent your mapping

**Comment by AsafFisher** [comment]
What if the binary is not an elf but a custom image that still has multiple sections that are allocated on different addresses?

I want FA to map these regions to their base address automatically if a signature exists for them

**Comment by doronz88** [comment]
I was talking about [simpleelf](https://github.com/doronz88/simpleelf) for if the mapping can be found easily before trying advanced signature matching. In general, that's the one I'm always using for creating a memory map of my firmware.

If you cannot know the mapping beforehand, I suggest either creating a PR for adding a simple command (maybe `add-code-seg <NAME>`/ `add-data-seg <NAME>`) or just [invoking a python signature](https://github.com/doronz88/fa#python-script-to-find-a-list-of-symbols).
